version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-novo
    ports:
      - "3309:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
    restart: always
